import type { NewsStory, Repo } from "./types";

/**
 * Static fallback data used when external APIs (GitHub / HN) fail or hit
 * rate limits. Keeps the UI alive in CI / preview environments and during
 * offline dev. The list is intentionally short and curated.
 */
export const FALLBACK_REPOS: Repo[] = [
  {
    id: 1,
    full_name: "openai/openai-cookbook",
    html_url: "https://github.com/openai/openai-cookbook",
    description: "Examples and guides for using the OpenAI API",
    stargazers_count: 60000,
    forks_count: 9800,
    pushed_at: new Date(Date.now() - 2 * 86400 * 1000).toISOString(),
    created_at: "2022-03-10T00:00:00Z",
    topics: ["openai", "gpt", "llm", "examples"],
    language: "Jupyter Notebook",
    owner: { login: "openai", avatar_url: "https://avatars.githubusercontent.com/u/14957082?v=4" },
  },
  {
    id: 2,
    full_name: "langchain-ai/langchain",
    html_url: "https://github.com/langchain-ai/langchain",
    description: "Build context-aware reasoning applications",
    stargazers_count: 95000,
    forks_count: 15300,
    pushed_at: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    created_at: "2022-10-17T00:00:00Z",
    topics: ["llm", "agent", "rag", "framework"],
    language: "Python",
    owner: { login: "langchain-ai", avatar_url: "https://avatars.githubusercontent.com/u/126733545?v=4" },
  },
  {
    id: 3,
    full_name: "ollama/ollama",
    html_url: "https://github.com/ollama/ollama",
    description: "Get up and running with Llama 3 and other LLMs locally",
    stargazers_count: 90000,
    forks_count: 7100,
    pushed_at: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    created_at: "2023-06-26T00:00:00Z",
    topics: ["llm", "llama", "language-model"],
    language: "Go",
    owner: { login: "ollama", avatar_url: "https://avatars.githubusercontent.com/u/151674099?v=4" },
  },
  {
    id: 4,
    full_name: "comfyanonymous/ComfyUI",
    html_url: "https://github.com/comfyanonymous/ComfyUI",
    description: "Powerful and modular diffusion model UI with a node graph",
    stargazers_count: 55000,
    forks_count: 5800,
    pushed_at: new Date(Date.now() - 3 * 86400 * 1000).toISOString(),
    created_at: "2023-01-17T00:00:00Z",
    topics: ["stable-diffusion", "image-generation", "diffusion"],
    language: "Python",
    owner: { login: "comfyanonymous", avatar_url: "https://avatars.githubusercontent.com/u/121283862?v=4" },
  },
  {
    id: 5,
    full_name: "huggingface/transformers",
    html_url: "https://github.com/huggingface/transformers",
    description: "State-of-the-art Machine Learning for PyTorch, TensorFlow, JAX",
    stargazers_count: 130000,
    forks_count: 25800,
    pushed_at: new Date(Date.now() - 1 * 86400 * 1000).toISOString(),
    created_at: "2018-10-29T00:00:00Z",
    topics: ["transformer", "language-model", "deep-learning", "framework"],
    language: "Python",
    owner: { login: "huggingface", avatar_url: "https://avatars.githubusercontent.com/u/25720743?v=4" },
  },
  {
    id: 6,
    full_name: "openai/whisper",
    html_url: "https://github.com/openai/whisper",
    description: "Robust Speech Recognition via Large-Scale Weak Supervision",
    stargazers_count: 70000,
    forks_count: 8200,
    pushed_at: new Date(Date.now() - 14 * 86400 * 1000).toISOString(),
    created_at: "2022-09-16T00:00:00Z",
    topics: ["speech", "asr", "whisper", "audio"],
    language: "Python",
    owner: { login: "openai", avatar_url: "https://avatars.githubusercontent.com/u/14957082?v=4" },
  },
  {
    id: 7,
    full_name: "ultralytics/yolov5",
    html_url: "https://github.com/ultralytics/yolov5",
    description: "YOLOv5 in PyTorch > ONNX > CoreML > TFLite",
    stargazers_count: 50000,
    forks_count: 16300,
    pushed_at: new Date(Date.now() - 5 * 86400 * 1000).toISOString(),
    created_at: "2020-05-18T00:00:00Z",
    topics: ["object-detection", "yolo", "computer-vision"],
    language: "Python",
    owner: { login: "ultralytics", avatar_url: "https://avatars.githubusercontent.com/u/26833451?v=4" },
  },
  {
    id: 8,
    full_name: "Significant-Gravitas/AutoGPT",
    html_url: "https://github.com/Significant-Gravitas/AutoGPT",
    description: "AutoGPT is the vision of accessible AI for everyone",
    stargazers_count: 165000,
    forks_count: 43500,
    pushed_at: new Date(Date.now() - 4 * 86400 * 1000).toISOString(),
    created_at: "2023-03-16T00:00:00Z",
    topics: ["agent", "autonomous", "autogpt", "agentic"],
    language: "Python",
    owner: { login: "Significant-Gravitas", avatar_url: "https://avatars.githubusercontent.com/u/130738209?v=4" },
  },
];

export const FALLBACK_NEWS: NewsStory[] = [
  {
    id: "fallback-1",
    title: "OpenAI announces new GPT model with improved reasoning",
    url: "https://openai.com/blog/",
    points: 420,
    num_comments: 130,
    author: "fallback",
    created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    source: "hackernews",
  },
  {
    id: "fallback-2",
    title: "Anthropic publishes interpretability research on Claude",
    url: "https://www.anthropic.com/research",
    points: 350,
    num_comments: 88,
    author: "fallback",
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    source: "hackernews",
  },
  {
    id: "fallback-3",
    title: "Show HN: Local LLM agent that runs entirely on CPU",
    url: "https://news.ycombinator.com/",
    points: 210,
    num_comments: 52,
    author: "fallback",
    created_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    source: "hackernews",
  },
];
